var emiPrincipal,emiRate,emiTenure,emi,piechart,barchart,psYear=[],psPrincipal=[],psInterest=[],psBalance=[];
jQuery(document).ready(function(){jQuery("#tabs").tabs({fx:{opacity:"show"}});jQuery(".tz_tab_widget .tab-tags a").css({backgroundColor:"#333333",color:"#E2E2E1"});jQuery(".tz_tab_widget .tab-tags a").hover(function(){jQuery(this).stop().animate({backgroundColor:"#A0410D",color:"#ffffff"},200)},function(){jQuery(this).stop().animate({backgroundColor:"#333333",color:"#E2E2E1"},500)});jQuery("#tabs img").css({backgroundColor:"#F9F8F8",borderColor:"#AFAEA6"});jQuery("#tabs img").hover(function(){jQuery(this).stop().animate({backgroundColor:"#222222",
borderColor:"#111111"},100)},function(){jQuery(this).stop().animate({backgroundColor:"#F9F8F8",borderColor:"#AFAEA6"},300)});jQuery(".post-lead img, a.fancybox img").css({backgroundColor:"#FCFCFC",borderColor:"#C8C8C2"});jQuery(".post-lead img, a.fancybox img").hover(function(){jQuery(this).stop().animate({backgroundColor:"#222222",borderColor:"#111111"},100)},function(){jQuery(this).stop().animate({backgroundColor:"#FCFCFC",borderColor:"#C8C8C2"},300)});jQuery(".single .post-lead img").css({backgroundColor:"#FCFCFC",
borderColor:"#C8C8C2"});jQuery(".single .post-lead img").hover(function(){jQuery(this).stop().animate({backgroundColor:"#FCFCFC",borderColor:"#C8C8C2"},100)},function(){jQuery(this).stop().animate({backgroundColor:"#FCFCFC",borderColor:"#C8C8C2"},300)});jQuery("#flickr .flickr_badge_image img").css({backgroundColor:"#C5C5C5",borderColor:"#111111"});jQuery("#flickr .flickr_badge_image img").hover(function(){jQuery(this).stop().animate({backgroundColor:"#222222",borderColor:"#111111"},100)},function(){jQuery(this).stop().animate({backgroundColor:"#C5C5C5",
borderColor:"#111111"},300)});jQuery("#sidebar #flickr .flickr_badge_image img").css({backgroundColor:"#FCFCFC",borderColor:"#AFAEA6"});jQuery("#sidebar #flickr .flickr_badge_image img").hover(function(){jQuery(this).stop().animate({backgroundColor:"#222222",borderColor:"#AFAEA6"},100)},function(){jQuery(this).stop().animate({backgroundColor:"#FCFCFC",borderColor:"#AFAEA6"},300)});jQuery("#primary .entry-title a").css({color:"#444444"});jQuery("#primary .entry-title a").hover(function(){jQuery(this).stop().animate({color:"#A0410D"},
100)},function(){jQuery(this).stop().animate({color:"#444444"},500)});jQuery("#top-nav ul").superfish({delay:200,animation:{opacity:"show",height:"show"},speed:"fast",autoArrows:false,dropShadows:false});var a=jQuery("#loanamountslider").slider({range:"min",value:jQuery("#Loan_Amount").val().replace(/[^\d\.]/g,""),min:100000,max:5000000,step:50000,slide:function(a,b){$("#Loan_Amount").val(Globalize.format(Math.round(b.value),"n","en-IN"))},change:function(){calculateEMI()}});jQuery("#Loan_Amount").change(function(){a.slider("value",
this.value.replace(/[^\d\.]/g,""))});var c=jQuery("#loan_intrslider").slider({range:"min",value:jQuery("#loan_intr").val(),min:10,max:20,step:0.25,slide:function(a,b){jQuery("#loan_intr").val(b.value)},change:function(){calculateEMI()}});jQuery("#loan_intr").change(function(){c.slider("value",this.value)});var b=jQuery("#tenureslider").slider({range:"min",value:jQuery("#tenure").val(),min:5,max:30,step:.5,slide:function(a,b){jQuery("#calc_Form input[type='radio']:checked").val()==
"tenure_years"?jQuery("#tenure").val(b.value):jQuery("#tenure").val(b.value*12)},change:function(){calculateEMI()}});jQuery("#tenure").change(function(){jQuery("#calc_Form input[type='radio']:checked").val()=="tenure_years"?b.slider("value",this.value):b.slider("value",this.value/12)});jQuery("#Loan_Amount").blur(function(){jQuery("#Loan_Amount").val(Globalize.format(Math.round(jQuery("#Loan_Amount").val().replace(/[^\d\.]/g,"")),"n","en-IN"))});jQuery("#loan_intr").blur(function(){jQuery("#loan_intr").val(Math.round(jQuery("#loan_intr").val().replace(/[^\d\.]/g,
"")*1E3)/1E3)});jQuery("#tenure").blur(function(){jQuery("#calc_Form input[type='radio']:checked").val()=="tenure_years"?jQuery("#tenure").val(Math.round(Math.round(jQuery("#tenure").val().replace(/[^\d\.]/g,"")*12)/12*100)/100):jQuery("#tenure").val(jQuery("#tenure").val().replace(/[^\d\.]/g,""))});$("#calc_Form input[type='radio']").change(function(){jQuery("#calc_Form input[type='radio']:checked").val()=="tenure_years"?jQuery("#tenure").val(Math.round(jQuery("#tenure").val().replace(/[^\d\.]/g,
"")/12*100)/100):jQuery("#tenure").val(Math.round(jQuery("#tenure").val().replace(/[^\d\.]/g,"")*12))});calculateEMI()});
function calculateEMI(){emiPrincipal=jQuery("#Loan_Amount").val().replace(/[^\d\.]/g,"");emiRate=jQuery("#loan_intr").val()/12/100;emiTenure=jQuery("#calc_Form input[type='radio']:checked").val()=="tenure_years"?Math.round(jQuery("#tenure").val()*12):jQuery("#tenure").val();emi=emiPrincipal*emiRate*(Math.pow(1+emiRate,emiTenure)/(Math.pow(1+emiRate,emiTenure)-1));jQuery("#emiamount span").text(Globalize.format(Math.round(emi),"n","en-IN"));jQuery("#emitotalinterest span").text(Globalize.format(Math.round(emi*
emiTenure-emiPrincipal),"n","en-IN"));jQuery("#emitotalamount span").text(Globalize.format(Math.round(emi*emiTenure),"n","en-IN"));calculatePaymentSchedule();displayPieChart();displayPaymentScheduleChart();displayPaymentScheduleTable()}
function calculatePaymentSchedule(){psYear=[];psPrincipal=[];psInterest=[];psBalance=[];var a=[],c=[],b=[];for(i=0;i<emiTenure/12;i++)psYear[i]=i+1;c[0]=emiPrincipal*emiRate;a[0]=emi-c[0];b[0]=emiPrincipal-a[0];for(i=1;i<emiTenure;i++)c[i]=b[i-1]*emiRate,a[i]=emi-c[i],b[i]=b[i-1]-a[i];for(i=b[emiTenure-1]=0;i<emiTenure/12;i++){a=emiTenure/12*12-i*12>=12?12:emiTenure/12*12-i*12;for(j=psInterest[i]=0;j<a;j++)psInterest[i]+=c[i*12+j];psInterest[i]=Math.round(psInterest[i]);psPrincipal[i]=Math.round(emi*
a-psInterest[i]);psBalance[i]=Math.round(b[(i+1)*12-(12-a)-1])}}
function displayPaymentScheduleChart(){barchart=new Highcharts.Chart({chart:{renderTo:"emibarchart",defaultSeriesType:"column"},title:{text:"EMI Chart"},xAxis:{categories:psYear,labels:{rotation:-45,align:"right",style:{font:"normal 9px Verdana, sans-serif"},formatter:function(){return"Year "+this.value}}},yAxis:{min:0,title:{text:"Interest + Principal"},stackLabels:{enabled:false,style:{fontWeight:"bold",color:Highcharts.theme&&Highcharts.theme.textColor||"gray"}},labels:{formatter:function(){return"Rs.  "+
Globalize.format(this.value,"n","en-IN")}}},legend:{align:"right",x:-10,verticalAlign:"top",y:20,floating:true,backgroundColor:Highcharts.theme&&Highcharts.theme.legendBackgroundColorSolid||"white",shadow:false},tooltip:{formatter:function(){return"<b>Year : "+this.x+"</b><br/>"+this.series.name+" : Rs. "+Globalize.format(this.y,"n","en-IN")+"<br/>Total : Rs. "+Globalize.format(this.point.stackTotal,"n","en-IN")}},plotOptions:{column:{stacking:"normal",dataLabels:{enabled:false,
color:Highcharts.theme&&Highcharts.theme.dataLabelsColor||"white"}}},series:[{name:"Principal",data:psPrincipal},{name:"Interest",data:psInterest}]})}
function displayPaymentScheduleTable(){var a='<table><tr><td id="yhead">Year</td><td id="phead">Principal Amount</td><td id="ihead">Interest Amount</td><td id="bhead">Balance Amount</td></tr>';for(i=0;i<psYear.length;i++)a+="<tr><td>"+psYear[i]+'</td><td class="currency">Rs. '+Globalize.format(psPrincipal[i],"n","en-IN")+'</td><td class="currency">Rs. '+
Globalize.format(psInterest[i],"n","en-IN")+'</td><td class="currency">Rs. '+Globalize.format(psBalance[i],"n","en-IN")+"</td></tr>";a+="</table>";jQuery("#emipaymenttable").html(a)}
function displayPieChart(){piechart=new Highcharts.Chart({chart:{renderTo:"emipiechart",plotBackgroundColor:null,plotBorderWidth:null,plotShadow:false},title:{text:"Total Payment"},tooltip:{formatter:function(){return"<b>"+this.point.name+"</b>: "+this.y+" %"}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true}},series:[{type:"pie",name:" ",data:[["Principal Home Loan Amount",Math.round(emiPrincipal*
100/(emi*emiTenure))],{name:"Total Interest",y:Math.round(100-emiPrincipal*100/(emi*emiTenure)),sliced:true,selected:true}]}]})};