<?php
	require 'scripts/functions.php';
	session_start();
	?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Home Loan Agreements India</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta http-equiv="Content-Language" content="en-us">
<meta name="keywords" content="Home loans, home loans India, home finance, housing loan, flexible, Home Loan clauses, Housing Finance Corporation (HFC), Reserve Bank of India (RBI), Discount Clause, Force Majeure Clause, Property prices, housing finance services, home loan repayment schemes, compare home loans, easy home loans, online home loans">
<meta name="Description" content="Home Loan Agreement: Learn about the points to be taken care of for your home loan agreement like fixed rate clause, Force Majeure Clause, Defining a default, Other kinds of default, Un-enforced discount clause, Other twisted clauses, etc on Deal4loans.com">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
<link href="source.css" rel="stylesheet" type="text/css" />
</head>
<body>
<?php include "middle-menu.php"; ?>
<div class="common-bread-crumb" style="margin:auto; margin-top:70px;"><a href="index.php">Home</a> > <a href="Contents_Articles.php">Articles Menu</a> > <a href="Home-Loan-Articles.php">Home Loan Articles</a> > Warning: ignorance is not bliss in a home loan agreement</div>
<div class="intrl_txt" style="margin:auto;">
  <div class="leftnewwrapper">
    <div style="width:100%; height:33; margin-top:15px; float:left; clear:right;">
      <h1 class="d4l-h1">Warning: ignorance is not bliss in a home loan agreement</h1>
      <div style="clear:both; height:15px;"></div>
      <!--class="lfttxtbar" -->
      <div>
        <p> <b>If you thought the loan documents were just a formality, think again. It is a contract skewed towards the lenders through various clauses buried in the fine print. We help you dig them out</b></p>
        <p> You have zeroed in on your new house, negotiated with the builder and the bank, and are all set to sign your <a href="http://www.deal4loans.com/">loan</a> papers. Buoyed by dreams of moving into a dream house that is owned by you, you are in a rush to get the deal sealed as quickly as possible. </p>
        <p>The loan document runs into 50 pages and its legal language so arcane that it does not even look like English. So you think, &ldquo;Hey, everyone signs the same agreement with the bank, what is there to read? It can&rsquo;t compromise my position; otherwise somebody would have pointed it out to me before&rdquo;. If this sounds like you, think again! There are a whole lot of potential dynamites in all the leading banks&rsquo; <a href="http://www.deal4loans.com/home-loans.php">home loan</a> agreements</p>
        <p>In the last few years, with the number of players and home loan offers multiplying manifold, getting a home loan has become a fairly easy process. Competition among <a href="http://www.deal4loans.com/home-loan-banks.php">housing finance companies</a> (HFCs) has ensured that at least you will have no dearth of lenders. </p>
        <p>But, almost as if a cartel was operating behind the scenes, the terms and conditions behind the home loan are framed in such a manner that the HFC acquires a strong legal cloak and your position is often compromised. Internationally, there are strong legislations ensuring that both the borrowers&rsquo; and lenders&rsquo; rights are expressed in all loan transactions. (See: When will we see truth in lending?) Unfortunately, in India this is not the case. </p>
        <p>The home loan agreement is the most important document here. But HFCs are often hesitant to provide you with a copy in advance so that this could be read and understood before you sign the agreement. HFCs use every method to refuse or delay handing over a copy to the borrower. Their excuse? &ldquo;No one really reads them,&rdquo; states a <a href="http://www.deal4loans.com/loans/banks/sbi-state-bank-of-india-loan/">State Bank of India</a> (SBI) official. </p>
        <p>It is important that you read the agreement before committing to the terms and conditions laid down by the HFC. Outlook Money attempts to assist you in this by pinpointing a few of the clauses in the agreement that side with HFCs. </p>
        <p><b>Reset clause on fixed rates:</b> With the current trend of rising interest rates, most borrowers choose to opt for a fixed rate loan. So does this mean your interest rate is locked at 11.5 per cent for the entire life of the loan? Not anymore. This is because banks have introduced a reset clause in their fixed rate home loan agreement that allows them to change the interest rate in the future, even on fixed rate loans. For instance, <a href="http://www.deal4loans.com/loans/banks/sbi-state-bank-of-india-loan/">SBI</a> has introduced a clause according to which it has the right to revise the fixed rate after two years. Corporation Bank and Canara Bank have reset options at the end of five years. </p>
        <p>Sachin Shinde, a Pune-based software engineer, thought he had made a &ldquo;prudent&rdquo; decision by opting for a fixed-rate home loan five years back from IDBI Bank. Three years after the date of disbursement, Shinde received a letter which said it was time for renewal of his loan and that the interest on his fixed home loan had been increased by 0.5 per cent. </p>
        <p>On checking with the bank he learned that there was a clause in the agreement that said the fixed rate was only for a period of three years and not for the entire tenure. </p>
        <p>A senior official with Bank of India points out that no lender can have an agreement that says a fixed rate can be fixed for the entire tenure of the loan, say 15 or 20 years, as this is likely to cause an asset-liability mismatch. </p>
        <p>Clearly, most borrowers are misled by the &lsquo;fixed rate&rsquo; loan. Read the loan agreement carefully, look out for the reset clause and quiz your HFC about it.</p>
        <p><b>Force Majeure Clause:</b> Often a semi-fixed rate loan gets advertised as fixed rate loan. You can find out the real picture only if you happen to read a clause such as this: &lsquo;Provided further that from time to time, the bank may in its sole discretion alter the rate of interest suitably and prospectively on account of change in the internal policies or if unforeseen or extraordinary changes in the money market conditions take place during the period of the agreement.&rsquo; </p>
        <p>This is called a force majeure clause, which allows an HFC to &lsquo;un-fix&rsquo; and raise the rate under exceptional circumstances. But what constitutes an exceptional circumstance for the HFC is ambiguous.</p>
        <p><b>Defining a default:</b> Also ambiguous and uncertain are the numerous clauses on what constitutes a default. A lay person cannot be faulted for thinking that default purely means non-payment of one or more loan installments. But HFCs go way beyond this. Here&rsquo;s a look at Citibank&rsquo;s home loan agreement as to what constitutes default&mdash;(i) &ldquo;where the borrower, or where the loan has been provided to more than one borrower, any of the borrowers is divorced or dies (applicable in case of an individual)&rdquo;, and (ii) &ldquo;if the borrower or any of the borrowers is/are involved in any civil litigation or criminal offence.&rdquo; Clearly, something is amiss. Says Ahmed Abdi, a Bombay High Court advocate, &ldquo;No loan agreement can impose restrictions on citizens&rsquo; constitutional rights to litigate. Even in the situation of the borrower himself being a respondent in any court case the person cannot be held guilty until the final court verdict.&rdquo;</p>
        <p><b>Other kinds of default:</b> What happens in case you face financial difficulties and miss paying a few EMIs? In the face of default, the attitude of some banks is appaling. Delhi-based couple Pallavi and Rahul Narvekar took a home loan from Standard Chartered Bank two years ago. Says Rahul, &ldquo;When my wife, who has high blood sugar content and blood pressure was recuperating from a surgery recently, they would call her for EMI payments, despite my request not to bother her.&rdquo; Now the Narvekars are switching to SBI. Calculate Emi at <a href="http://www.deal4loans.com/Contents_Calculators.php">EMI Calculator</a></p>
        <p>Can the HFC send rude recovery agents to your home? Under the law of the land, it cannot. Says Abdi, &ldquo;Possession of property or any other physical action has to be through a court order under some legislation.&rdquo; An Allahabad High Court judgment in a car loan case can provide an indication. In August 2005, an ICICI Bank car loan borrower, Someshwari Prasad, (an advocate with Allahabad High Court) was abducted by collection agents of the bank and taken to the bank branch where he was beaten up by bank officials. Prasad filed an FIR with the police and had the bank officials and collection agents arrested. </p>
        <p>Hearing a habeas corpus petition filed by <a href="http://www.deal4loans.com/loans/banks/icici-bank-icici/">ICICI Bank</a> to release its arrested officials, the Allahabad High Court raised numerous questions about recovery agents and the process. It asked, &ldquo;Whether ICICI Bank or its collection agency can take coercive action against the borrower by snatching the vehicles or taking possession of the property without following the procedure established by law and take further coercive action by locking the individual borrower in the bank or at some other place?&rdquo; </p>
        <p>Says Prasad, &ldquo;Direct snatching is not provided by any law and in fact violates multiple provisions of the Indian Penal Code.&rdquo; </p>
        <p>Lending HFCs&rsquo; legal remedy for defaults on loans having outstanding amount of Rs 10 lakh and above, is to file a suit against the borrower under the Sarfaesi Act (Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act). For lower amounts they can file a suit in the civil court.</p>
        <p><b>Security cover when property prices decline:</b> You may be paying your EMIs on time. But when property prices crash you may be asked to provide security over and above the home mortgage. The clause that enables this reads: &lsquo;the bank may declare all sums outstanding under the home loan (including the principal, interest, charges, expenses) to become due and payable forthwith if the value of the property or any security (including guarantees) created or tendered by the borrower, in the sole discretion and decision of the bank, depreciates entitling the bank to call for further security and the borrower fails to give additional security.&rsquo; </p>
        <p>The bank will deem you to be a defaulter if you don&rsquo;t give the additional security. <br />
          <br />
          <b>Direct disbursement to builder:</b> A clause in <a href="http://www.deal4loans.com/icici-hfc-home-loan.php">ICICI home loan</a> agreement stipulates that the &ldquo;disbursement of the loan may be made directly to the builder or developer and in the case of a ready-built property to the vendor thereof and/or in such other manner as may be decided solely by bank.&rdquo; </p>
        <p>&ldquo;This clause gives too much leeway to the bank&rdquo;, says a Delhi-based lawyer. It is the borrower whose original property papers are retained with the bank, so ideally the bank should disburse the loan amount to the borrower and not to the builder. </p>
        <p><b>Un-enforced discount clause:</b> A Delhi-based executive, who works with a fashion house, took a home loan from <a href="http://www.deal4loans.com/loans/banks/hdfc-bank-hdfc-ltd/">HDFC</a> in 2004 on a house that was under construction, the possession of which was to be given in April 2006. The bank issued the cheque on the developer&rsquo;s name. Last month, he finally received the possession of the house, more than six months late. He says, &ldquo;The documents had a penalty clause that stipulates that if the possession of the house is delayed the developer will give a discount.&rdquo; While taking possession Dasgupta asked the builder to adhere to the delayed delivery clause. &ldquo;But the builder told us to take the keys of the house or leave it and that they are not running short of buyers who are ready to take the house even at an escalated price now&rdquo;. He feels that his HFC should have taken a tough stand with the builder on the delayed delivery.</p>
        <p><b>Assignment to third parties:</b> HFCs take your authorisation to assign collection and administration rights on your loan to third parties. A Citibank home loan agreement does it through this clause: &ldquo;Borrower expressly accepts that the bank shall be entitled to appoint third parties as the bank may select which gives to such third party all or any of its functions, rights and powers under this agreement including the authority to collect MMR (minimum monthly repayment) due by the borrower.&rdquo; </p>
        <p>Elsewhere, this agreement further states, &ldquo;the bank may assign any of its rights or obligations herein without any approval or consent of the borrower.&rdquo; This is clearly an unfair provision. Suggests Abdi, &ldquo;You look at a bank&rsquo;s reputation and credibility before entering into a loan agreement with it; so when an unknown, undisclosed, and potentially un-credible third party takes over, you should be allowed an exit option whereby you could move your home loan from bank X to bank Y.&rdquo; Again, unfortunately, no HFC offers such an exit option. </p>
        <p><b>Other twisted clauses:</b> Some clauses are ambiguously worded. Take this one for example: &lsquo;The bank/HFC will be notified of any change in the borrower&rsquo;s employment, business or profession well in advance.&rsquo; Questions a Delhi-based lawyer, &ldquo;The clause of &lsquo;well in advance&rsquo; is very vague. How much in advance will be well in advance, the bank should specify that.&rdquo; </p>
        <p>In your early EMIs, the proportion of interest charge is far higher than principal repayment. Says H.K. Awasthi, a legal advisor to Delhi -based consumer rights organisation, Consumer Voice, &ldquo;Banks should recover the interest and principal amount simultaneously&rdquo;. </p>
        <p>Pre-loan procedure is also full of potholes. Points out Awasthi: &ldquo;For document processing, banks charge around one per cent of the loan amount which should be refunded if the banks ultimately deny the loan.&rdquo; The legal jurisdiction in case of disputes is always at the place where the HFC&rsquo;s central office is located. Says Abdi, &ldquo;Individual borrowers, who are spread across the country, cannot afford to travel long-distance to seek legal enforceability of their rights.&rdquo; </p>
        <p>Cross default is another faulty clause where the HFC deems you a defaulter on your home loan if you have made any kind of default in any other loan or facility with the same HFC. Argues Abdi, &ldquo;These are two different transactions and each one&rsquo;s performance or non-performance should be measured independently.&rdquo; </p>
        <p>The biggest twist in the loan agreement is in the amendment clause. This is a sample from a Citibank home loan agreement: &ldquo;The bank shall at its sole discretion alter the terms of this agreement by written intimation sent to the borrower by courier. Any amendment proposed by the borrower shall be valid only if made by a written agreement signed by both the parties.&rdquo; So there you are, heads they win, tails you lose. </p>
        <p><b>What you should do:</b> Asking for what is fair and due to you is not that difficult. Make sure that that you bring these lopsided clauses to the notice of the HFC, suggest changes and bargain hard to get them implemented. If the HFCs persist, then lodge a formal complaint with National Housing Bank (NHB), a wholly-owned subsidiary of the Reserve Bank of India. As recently as September 2006, NHB had come out with guidelines for HFCs regarding fair practices (see: Code of Conduct). Says S. Sridhar, chairman and managing director, NHB, &ldquo;Borrowers from HFCs can send their complaints to us but complaints against banks&rsquo; home loans are dealt with by RBI.&rdquo; </p>
        <p>Are NHB&rsquo;s guidelines effective and enforceable? Sridhar claims that NHB monitors compliance with the mandatory and other requirements through the mechanism of off-site returns submitted by HFCs and on-site inspection of HFCs. He says, &ldquo;HFCs are expected to function in a fair and transparent manner and follow customer friendly practices.&rdquo; </p>
        <p>So, if your home loan is from a non-bank HFC, then write in your observations on all the unfair clauses of your agreement to NHB at nhbh01@bol.net.in or through its website www.nhb.org.in. For banks, write in to RBI at helpprd@rbi.org.in or go through its website www.rbi.org.in. It&rsquo;s time that borrowers make an effort to balance the scale.<br />
          <br />
          <b>Source :</b> www.outlookmoney.com</p>
      </div>
    </div>
  </div>
  <div class="newright-panel">
    <?php include "RightPL1.php"; ?>
  </div>
</div>
<?php include "footer_sub_menu.php"; ?>
</body>
</html>
