This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://serviceimpl.alobr.valuemomentum.com" xmlns:intf="http://serviceimpl.alobr.valuemomentum.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://serviceimpl.alobr.valuemomentum.com">
<!--
WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)
-->
<wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://serviceimpl.alobr.valuemomentum.com">
<element name="invokeBRE">
<complexType>
<sequence>
<element name="objModel" type="xsd:string"/>
<element name="rawData" type="xsd:string"/>
</sequence>
</complexType>
</element>
<element name="invokeBREResponse">
<complexType>
<sequence>
<element name="invokeBREReturn" type="xsd:string"/>
</sequence>
</complexType>
</element>
<element name="retrieveAsyncResponse">
<complexType>
<sequence>
<element name="sequenceID" type="xsd:string"/>
</sequence>
</complexType>
</element>
<element name="retrieveAsyncResponseResponse">
<complexType>
<sequence>
<element name="retrieveAsyncResponseReturn" type="xsd:string"/>
</sequence>
</complexType>
</element>
<element name="invokeBREWithNoRawData">
<complexType>
<sequence>
<element name="objModel" type="xsd:string"/>
</sequence>
</complexType>
</element>
<element name="invokeBREWithNoRawDataResponse">
<complexType>
<sequence>
<element name="invokeBREWithNoRawDataReturn" type="xsd:string"/>
</sequence>
</complexType>
</element>
</schema>
</wsdl:types>
<wsdl:message name="invokeBREWithNoRawDataResponse">
<wsdl:part element="impl:invokeBREWithNoRawDataResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="retrieveAsyncResponseResponse">
<wsdl:part element="impl:retrieveAsyncResponseResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="invokeBRERequest">
<wsdl:part element="impl:invokeBRE" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="invokeBREResponse">
<wsdl:part element="impl:invokeBREResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="invokeBREWithNoRawDataRequest">
<wsdl:part element="impl:invokeBREWithNoRawData" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="retrieveAsyncResponseRequest">
<wsdl:part element="impl:retrieveAsyncResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:portType name="RupeePowerService">
<wsdl:operation name="invokeBRE">
<wsdl:input message="impl:invokeBRERequest" name="invokeBRERequest"></wsdl:input>
<wsdl:output message="impl:invokeBREResponse" name="invokeBREResponse"></wsdl:output>
</wsdl:operation>
<wsdl:operation name="retrieveAsyncResponse">
<wsdl:input message="impl:retrieveAsyncResponseRequest" name="retrieveAsyncResponseRequest"></wsdl:input>
<wsdl:output message="impl:retrieveAsyncResponseResponse" name="retrieveAsyncResponseResponse"></wsdl:output>
</wsdl:operation>
<wsdl:operation name="invokeBREWithNoRawData">
<wsdl:input message="impl:invokeBREWithNoRawDataRequest" name="invokeBREWithNoRawDataRequest"></wsdl:input>
<wsdl:output message="impl:invokeBREWithNoRawDataResponse" name="invokeBREWithNoRawDataResponse"></wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="RupeePowerServiceSoapBinding" type="impl:RupeePowerService">
<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="invokeBRE">
<wsdlsoap:operation soapAction=""/>
<wsdl:input name="invokeBRERequest">
<wsdlsoap:body use="literal"/>
</wsdl:input>
<wsdl:output name="invokeBREResponse">
<wsdlsoap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="retrieveAsyncResponse">
<wsdlsoap:operation soapAction=""/>
<wsdl:input name="retrieveAsyncResponseRequest">
<wsdlsoap:body use="literal"/>
</wsdl:input>
<wsdl:output name="retrieveAsyncResponseResponse">
<wsdlsoap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="invokeBREWithNoRawData">
<wsdlsoap:operation soapAction=""/>
<wsdl:input name="invokeBREWithNoRawDataRequest">
<wsdlsoap:body use="literal"/>
</wsdl:input>
<wsdl:output name="invokeBREWithNoRawDataResponse">
<wsdlsoap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="RupeePowerServiceService">
<wsdl:port binding="impl:RupeePowerServiceSoapBinding" name="RupeePowerService">
<wsdlsoap:address location="http://14.140.27.7:9080/RupeePowerWebService/services/RupeePowerService"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>