<?php
session_start();
require 'scripts/session_check.php';
require 'scripts/db_init.php';
require 'scripts/functions.php';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="css/apply-personal-loans-lp-styles-new2-11-2015.css" type="text/css" rel="stylesheet" />
<link rel="stylesheet" href="css/pl_apply-tab_styles-new11-2-2015.css" />
<link href="css/personal-loans-new-lp-11-2-2015.css" type="text/css" rel="stylesheet" />
<title>Check Credit Score</title>
<meta name="keywords" content="Check Credit Score" />
<meta name="description" content="Check Credit Score" />
<link href="css/personal-loan-styles.css" type="text/css" rel="stylesheet"  />
<script Language="JavaScript" Type="text/javascript" src="scripts/common.js"></script>
</head>
<body>
<?php include "middle-menu.php";
 ?>
<div class="d4l_inner_wrapper">
<div style="margin-top:70px;"></div>
<div  class="common-bread-crumb"><a href="index.php">Home</a> > Consent</div>
<div style="margin:auto;">
  <div >
    <div>
      <div style="clear:both;"></div>
      <div style="clear:both; height:15px;"></div>
      <div id="txt">
          <p><strong>CONSENT IN RELATION TO ACCESS TO CREDIT INFORMATION THROUGH EXPERIAN</strong><br />
           This End User Agreement (the "Agreement") is made between you (the "User" or "You") and   ("Deal4loans"), a private limited company. Deal4loans " "Us" or "We", which term shall include its successors and permitted assigns). The User and Deal4loans shall be collectively referred to as the "Parties" and individually as a "Party"
           <br />
           YOU HEREBY APPOINT Deal4loans AS YOUR AUTHORISED REPRESENTATIVE TO RECEIVE YOUR CREDIT INFORMATION FROM EXPERIAN.
                       
           </p>
          <p>&nbsp;</p>
          <p><strong>BY EXECUTING THIS AGREEMENT 1 CONSENT FORM, YOU ARE EXPRESSLY AGREEING TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE, AGGREGATE SCORES, INFERENCES, REFERENCES AND DETAILS (AS DEFINED REFERRED AS "CREDIT INFORMATION"). YOU HEREBY ALSO IRREVOCABLY AND UNCONDITIONALLY CONSENT TO SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO you AND Deal4loans BY USING EXPERIAN TOOLS, ALGORITHMS AND DEVICES AND YOU HEREBY AGREE, ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.</strong></p>
          <p><br />
            <strong><u>Terms and Conditions</u></strong><strong>: </strong><br />
            <strong>Information Collection, Use,  Confidentiality, No-Disclosure and Data Purging</strong><br />
            <strong>Deal4loans</strong> shall access your Credit Information as your authorized representative  and <strong>Deal4loans</strong> shall use the Credit Information for limited End Use Purpose consisting  of and in relation to the services proposed to be availed by you from <strong>Deal4loans</strong>. We shall not aggregate,  retain, store, copy, reproduce, republish, upload, post, transmit, sell or rent  the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed  herein and in furtherance to CICRA. <br />
The Parties agree to protect  and keep confidential the Credit Information both online and offline.<br />
The Credit Information  shared by you, or received on by us on your behalf shall be destroyed, purged,  erased promptly within <em>1 (one) Business  Day</em> of upon the completion of the transaction/ End Use Purpose for which  the Credit Information report was procured. <strong></strong><br />
<strong>Governing Law and Jurisdiction</strong><br />
The relationship between you and <strong>Deal4loans</strong> shall be  governed by laws of India and all claims or disputes arising there from shall  be subject to the exclusive jurisdiction of the courts of Mumbai. <strong></strong><br />
<strong>Definitions:</strong><br />
Capitalised terms  used herein but not defined above shall have the following meanings:<br />
<strong>Business  Day</strong> means a day (other than a public holiday) on which banks are open for  general business in Mumbai. <br />
<strong>Credit Information Report</strong> means the  credit information / scores/ aggregates / variables / inferences or reports  which shall be generated by Experian;<br />
<strong>Credit Score</strong> means the score which  shall be mentioned on the Credit Information Report which shall be computed by  Experian.<br />
<strong>CICRA</strong> shall mean the Credit  Information Companies (Regulation) Act, 2005 read with the Credit Information  Companies Rules, 2006 and the Credit Information Companies Regulations, 2006,  and shall include any other rules and regulations prescribed thereunder.<br />
 PLEASE READ THE  ABOVEMENTIONED TERMS AND CONDITIONS AND CLICK ON &ldquo;ACCEPT&rdquo; FOLLOWED BY THE LINK  BELOW TO COMPLETE THE AUTHORISATION PROCESS FOR SHARING OF YOUR CREDIT  INFORMATION BY EXPERIAN WITH YOU and <strong>Deal4loans</strong> IN ITS CAPACITY AS YOUR AUTHORISED  REPRESENTATIVE. </p>
BY CLICKING &quot;<strong>ACCEPT</strong>&quot; YOU  AGREE AND ACCEPT THE DISCLAIMERS AND TERMS AND CONDITIONS SET OUT HEREIN.
<p>&nbsp; </p>
      
      </div>
     
    </div>
  </div>
  <div class="right-panel">
    <?php //include "right-widget.php"; ?>
  </div>
</div>
<div></div>
</div>

<?php include("footer_sub_menu.php"); ?>
<?php print_r($_GET); ?>
</body>
</html>