<?php
//error_reporting(E_ALL);
require 'scripts/db_init.php';

$today=Date('Y-m-d');
$tomorrow  = mktime(0, 0, 0, date("m")  , date("d")-1, date("Y"));
$currentdate=date('Y-m-d',$tomorrow);
$mindate=$currentdate." 00:00:00";
$maxdate=$today." 23:59:59";

$tatacapitallog="Select * From webservice_bidder_details Where (mail_sent=0 and bidderid in (5247,5250,5235,5236,5237,5243,5241,5242,5240,5245,5239,5319,5320,5321,5422) and doe between '".$mindate."' and '".$maxdate."')";
//$tatacapitallog="Select * from webservice_bidder_details Where (=434370)";
$tatacapitalresult=ExecQuery($tatacapitallog);
 while($plrow=mysql_fetch_array($tatacapitalresult))
 {
	$websrvid = $plrow["websrvid"];
	$cust_requestid = $plrow["cust_requestid"]; 
	$feedback = $plrow["feedback"];
	$webfeedback=$feedback;
	$expires = preg_split('/Lead id/', $webfeedback);
	array_shift($expires);
	$strcheck=implode(" ",$expires);
	$check=explode(" ",$strcheck);
	echo $Leadid=$check[0];
	list($firstprt,$lastprt) = split('["]',$Leadid);

$tataqry="Select Name,Email From Req_Loan_Personal Where (RequestID=".$cust_requestid.")";
$tatatataqryresult=ExecQuery($tataqry);
$row=mysql_fetch_array($tatatataqryresult);
echo $Name = $row["Name"];
echo $Email = $row["Email"];

	 if($lastprt>0 && strlen($Email)>0)
	 {
$tatacp_mailer="<table align='center' style='max-width:650px; border:solid thin #dad9d9;' width='600' border='0' cellpadding='2' cellspacing='0' >
<tr>
<td height='35' colspan='2'  align='right' bgcolor='#0c74b4' style='font-family:Arial, Helvetica, sans-serif; font-size:18px; color:#FFFFFF; padding-right:5px;'>Deal4loans.com</td>
</tr>
<tr>
<td colspan='2' bgcolor='#FFFFFF'>&nbsp;</td>
</tr>
<tr>
<td width='19' bgcolor='#FFFFFF'>&nbsp;</td>
<td width='581' bgcolor='#FFFFFF' style='font-family:Verdana, Geneva, sans-serif; color:#404040; font-size:13px;'>Dear ".$Name." ,</td>
</tr>
<tr>
<td >&nbsp;</td>
<td style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>Thank you for choosing Deal4loans.com, we are pleased to inform you that your registration for Personal Loan has been successful. <br><br>
As a process of application distinctively for Tata capital Personal Loan. Please take a note of the reference id generated by Tata capital for future reference and tracking of your personal loan application. You will soon be contacted by Tata capital for further process.
</td>
</tr>
<tr>
  <td bgcolor='#FFFFFF'>&nbsp;</td>
  <td bgcolor='#FFFFFF'>&nbsp;</td>
</tr>
<tr>
  <td bgcolor='#fffbf0'>&nbsp;</td>
<td bgcolor='#fffbf0'><table width='100%' style='max-width:300px;' align='left' cellpadding='0' cellspacing='0'>
<tr>
<td width='162' height='15' style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>Bank name</td>
<td width='13' height='15' align='left' style='font-family:Verdana, Geneva, sans-serif; font-size:11px;'>:</td>
<td width='411' height='15' style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>Tata Capital </td>
</tr>
<tr>
<td width='162' height='15' style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>Reference id </td>
<td width='13' height='15' align='left' style='font-family:Verdana, Geneva, sans-serif; font-size:11px;'>:</td>
<td width='411' height='15' style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>".$lastprt."</td>
</tr>  
  </table></td>
</tr>
<tr>
  <td bgcolor='#FFFFFF'>&nbsp;</td>
  <td bgcolor='#FFFFFF'>&nbsp;</td>
</tr>
<tr>
<td bgcolor='#FFFFFF'>&nbsp;</td>
<td  style='font-family:Verdana, Geneva, sans-serif; font-size:14px; line-height:17px;'><u>Please note : The above mentioned reference id is only to be used for your selection of Tata capital at deal4loans for your Personal Loan application .For other Bank selected (if any), you can expect a call from respective bank representatives within 24 hrs.</u></td>
</tr>
<tr>
  <td height='10' colspan='2' bgcolor='#FFFFFF'></td>
</tr>

<tr>
  <td colspan='2' bgcolor='#FFFFFF'  style='border-bottom:thin solid #f2f2f2;' height='2'></td>
</tr>
<tr>
  <td colspan='2' bgcolor='#FFFFFF'  height='5'></td>
</tr>
<tr>
  <td colspan='2' bgcolor='#FFFFFF' style='color:#404040; font-size:9px; font-family:Verdana, Geneva, sans-serif;'></td>
</tr>
<tr>
  <td bgcolor='#FFFFFF'>&nbsp;</td>
  <td bgcolor='#FFFFFF'  style='color:#404040; font-size:11px; font-family:Verdana, Geneva, sans-serif;'><strong>Disclaimer:</strong>The rate quotes offered by the bank representatives are solely on the bank's discretion. We do not hold any responsibility for any miscommunication/ misrepresentation of the information  given by the bank's sales representative.</td>
</tr>
<tr><td colspan='2'>&nbsp;</td></tr>
<tr><td></td><td style='font-family:Verdana, Geneva, sans-serif; font-size:14px;'>Warm Regards,<br>
Team Deal4Loans
</td></tr>
<tr>
  <td colspan='2' bgcolor='#FFFFFF'>&nbsp;</td>
</tr>
</table>";
//echo $tatacp_mailer."<br><br>";

	$headers = "From: deal4loans <no-reply@deal4loans.com>";
	$semi_rand = md5( time() ); 
	$mime_boundary = "==Multipart_Boundary_x{$semi_rand}x"; 
	$headers .= "\nMIME-Version: 1.0\n" . 
			"Content-Type: multipart/mixed;\n" . 
			" boundary=\"{$mime_boundary}\""."\n";
	$headers .= "Bcc: extra4testingnew@gmail.com"."\n";
	$message = "This is a multi-part message in MIME format.\n\n" . 
		"--{$mime_boundary}\n" . 
		"Content-Type: text/html; charset=\"iso-8859-1\"\n" . 
		"Content-Transfer-Encoding: 7bit\n\n" . 
		$tatacp_mailer . "\n\n";
$SubjectLine ="Thanks for Registering for Personal Loan at deal4loans.com";
//$Email="ranjana5chauhan@gmail.com";
	//echo $Type_Loan;
	if(isset($Email))
	{
		mail($Email, $SubjectLine, $message, $headers);
	}

$tataupdate="Update webservice_bidder_details set mail_sent=1 Where websrvid =".$websrvid;
$tataupdateresult=ExecQuery($tataupdate);

	 }
	 else
	 {
		 $tataupdate="Update webservice_bidder_details set mail_sent=2 Where websrvid =".$websrvid;
		 $tataupdateresult=ExecQuery($tataupdate);
	 }
 }
?>
