<?php
//print_r($_SERVER);
require 'scripts/functions.php';
session_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<title>Terms of Use - Deal4loans.com's Services | Online Loan Application And Information</title>
<meta name="keywords" content="home loans, car loans, personal loans, loans against property, credit cards, online loan application, loan information">
<meta name="Description" content="Deal4Loans is an online loan information portal, provides valuable information on all types of loans in India offered by top banks. Read online information on home loans, car loans, personal loans, loans against property, loan providers and credit cards.">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
<link href="source.css" rel="stylesheet" type="text/css" />
<link href="css/common-d4l-styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
<?php include "middle-menu.php"; ?>
<div class="lac-main-wrapper">
  <div class="text12" style="margin:auto; height:11px; margin-top:70px; color:#4c4c4c;"><u><a href="index.php" class="text12" style="color:#0080d6;" >Home</a></u> > Terms of Use</div>
  <div style="clear:both; height:15px;"></div>
  <div>
    <table>
      <tr>
        <td align="center"><h1 style="margin-top:0px;font-size:28px; text-transform:none;"><strong>Terms of Use</strong></h1></td>
      </tr>
    </table>
    <div >
      <p>Deal4loans.com. Is a website (the "Site") operated by WRS Info India Pvt. Ltd ("WRS"). WRS provides its services to you subject to the following conditions. Before you may use the Site, you must read and accept all of the terms and conditions in, and linked to, this Terms of Use and the linked Privacy Policy. We strongly recommend that, as you read this ToU, you also access and read the linked information, since it is incorporated into and hereby made part of this ToU. This ToU is effective upon acceptance. Use of any functionality of the Site constitutes acceptance of this ToU. If this ToU conflicts with any other documents, the ToU will control for the purposes of usage of the Site. If you do not agree to be bound by this ToU and the Privacy Policy, you may not use the Site in any way. Be sure to return to this page periodically to review the most current version of the ToU. We reserve the right at any time, at our sole discretion, to change or otherwise modify the TOS without prior notice, and your continued access or use of this Site signifies your acceptance of the updated or modified TOS.<br />
        <br />
        <b>1. Description of Services</b><br />
        In the Site, WRS provides users with access to information primarily about Financial and Utility Services including but not restricted to, Loans, Credit Cards, Communication and Entertainment Services (the "Service"). You are responsible for obtaining access to the Site, and that access may involve third-party fees (such as Internet service provider or airtime charges). In addition, you must provide and are responsible for all equipment necessary to access the Site. By making use of this site, and furnishing your personal / contact details, you hereby agree that you are interested in availing and purchasing the services that you have selected. You hereby agree that WRS may contact you either electronically or through phone, to understand your interest in the selected products and services and to fulfill your demand. You also agree that WRS reserves the right to make your details available to partners and you may be contacted by the partners for information and for sales through email, telephone and/or sms. You agree to receive promotional materials and/or special offers from WRS through email or sms.<br />
        <br />
        <b>2. License and Site Access</b><br />
        WRS grants you a limited license to access and make personal use of the Site and the Service. This license does not include any downloading or copying of any kind of information for the benefit of another individual, vendor or any other third party; caching, unauthorized hypertext links to the Site and the framing of any Content available through the Site uploading, posting, or transmitting any content that you do not have a right to make available (such as the intellectual property of another party); uploading, posting, or transmitting any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; any action that imposes or may impose (in WRS's sole discretion) an unreasonable or disproportionately large load on WRS's infrastructure; or any use of data mining, robots, or similar data gathering and extraction tools. You may not bypass any measures used by WRS to prevent or restrict access to the Site. Any unauthorized use by you shall terminate the permission or license granted to you by WRS. By using the Site you agree not to: (i) use this Site or its contents for any commercial purpose; (ii) make any speculative, false, or fraudulent transaction or any transaction in anticipation of demand; (iii) access, monitor or copy any content or information of this Site using any robot, spider, scraper or other automated means or any manual process for any purpose without our express written permission; (iv) violate the restrictions in any robot exclusion headers on this Site or bypass or circumvent other measures employed to prevent or limit access to this Site; (v) take any action that imposes, or may impose, in our discretion, an unreasonable or disproportionately large load on our infrastructure; (vi) deep-link to any portion of this Site (including, without limitation, the purchase path for any service) for any purpose without our express written permission; or (vii) "frame", "mirror" or otherwise incorporate any part of this Site into any other website without our prior written authorization.<br />
        <br />
        <b>3. Eligibility</b><br />
        The Service is not available to minors under the age of 18 or to any users suspended or removed from the system by WRS for any reason<br />
        <br />
        <b>4. Your Account</b><br />
        In consideration of your use of the Site, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of India or other applicable jurisdiction and will only use the Site to make legitimate purchases for you or for another person for whom you are legally authorized to act (and will inform such other persons about the ToU and/or Privacy Policy) that apply to the purchase you have made on their behalf (including all rules and restrictions applicable thereto). You also agree to provide true, accurate, current and complete information about yourself as prompted by the Site. If you provide any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or WRS has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, WRS has the right to refuse any and all current or future use of the Site (or any portion thereof). Notwithstanding the above, we retain the right at our sole discretion to deny access to anyone to the Site and the Services we offer, at any time and for any reason, including, but not limited to, for violation of the ToU or Privacy Policy.<br />
        <br />
        <b>5. Submitted Content</b><br />
        WRS does not claim ownership of any materials you make available through the Site. At WRS’s sole discretion, such materials may be included in the Service in whole or in part or in a modified form. With respect to such materials you submit or make available for inclusion on the Site, you grant WRS a perpetual, irrevocable, non-terminable, worldwide, royalty-free and non-exclusive license to use, copy, distribute, publicly display, modify, create derivative works, and sublicense such materials or any part of such materials (as well as use the name that you submit in connection with such submitted content). You hereby represent, warrant and covenant that any materials you provide do not include anything (including, but not limited to, text, images, music or video) to which you do not have the full right to grant the license specified in this Section 4. We take no responsibility and assume no liability for any submitted content posted or submitted by you. We have no obligation to post your comments; we reserve the right in our absolute discretion to determine which comments are published on the Site. If you do not agree to these terms and conditions, please do not provide us with any submitted content. You agree that you are fully responsible for the content you submit. You are prohibited from posting or transmitting to or from this Site: (i) any unlawful, threatening, libelous, defamatory, obscene, pornographic, or other material or content that would violate rights of publicity and/or privacy or that would violate any law; (ii) any commercial material or content (including, but not limited to, solicitation of funds, advertising, or marketing of any good or services); and (iii) any material or content that infringes, misappropriates or violates any copyright, trademark, patent right or other proprietary right of any third party. You shall be solely liable for any damages resulting from any violation of the foregoing restrictions, or any other harm resulting from your posting of content to this Site.<br />
        <br />
        <b>6. Disclaimer of Online Availability,Impressions, And Click-Throughs</b><br />
        In addition to the other disclaimers and limitations discussed in this notice, there are no guarantees and no warranties regarding online availability, impressions, and click-through of www.deal4loans.com, its web pages, and any material, information, links, or content presented on the web pages at www.deal4loans.com, its web pages, and any material, information, links, or content presented on the web pages at www.deal4loans.com, may be unavailable for online access at anytime. Advertising sponsors and advertising must be approved by WRS before the posting of any advertising material, information, links, content, banners, and graphics on www.deal4loans.com. WRS reserves the right to accept or to reject any advertising sponsor or any advertising for any reason.<br />
        <br />
        <b>7. License Disclaimer</b><br />
        Nothing on any WRS’s website shall be construed as conferring any license under any of WRS’s or any third party's intellectual property rights, whether by estoppel, implication, or otherwise.<br />
        <br />
        <b>8. Local Laws</b>
        <bt>
        WRS controls and operates this Website from its headquarters in Delhi, India and makes no representation that the materials on the website are appropriate or available for use in other locations. If you use this Website from other locations, you are responsible for compliance with applicable local laws including but not limited to the export and import regulations of other countries. Unless otherwise explicitly stated, all marketing or promotional materials found on this Website are solely directed to individuals, companies or other entities located in India and comply with the laws prevailing for the time being in force in India. Disputes if any shall be subject to the exclusive jurisdiction of Courts at Delhi.<br />
        <br />
        <b>9. Limitation of Liability</b><br />
        You expressly understand and agree that WRS and its subsidiaries, affiliates, officers, employees, agents, partners and licensors shall not be liable to you for any direct, indirect, incidental, special, consequntial or exemplary damages, including, but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if jetsetter has been advised of the possibility of such damages), resulting from use of the site, content or any related services. If, despite the limitation above, WRS or its Affiliates are found liable for any loss or damage which arises out of or in any way connected with any of the occurrences described above, then the liability of WRS and/or Its Affiliates will in no event exceed, in the aggregate, the greater of (a) the service fees you paid to WRS in connection with such transaction(s) on this Site, or (b) Rupees One Hundred only (INR 100) The limitation of liability reflects the allocation of risk between the parties. The limitations specified in this section will survive and apply even if any limited remedy specified in these terms is found to have failed of its essential purpose. The limitations of liability provided in these terms inure to the benefit of WRS, Its Affiliates, and/or their respective suppliers.<br />
        <br />
        <b>10. Indemnity</b><br />
        You agree to indemnify and hold WRS (and its officers, directors, agents, subsidiaries, joint ventures, and employees) harmless from any and against any claims, causes of action, demands, recoveries, losses, damages, fines, penalties or other costs or expenses of any kind or nature, including reasonable attorneys' fees, or arising out of or related to your breach of this ToU, your violation of any law or the rights of a third party, or your use of the Site.<br />
        <br />
        <b>11. Electronic Communication</b><br />
        When you use the Site, you are communicating with WRS electronically. You consent to receive communications from WRS electronically. WRS may communicate with you by email or by posting notices on the Site or by phone or usually available means of communication. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing<br />
        <br />
        <b>12. Site-Provided message Postings</b><br />
        The Site may provide users with the ability to post messages on the Site. WRS is under no obligation to review any messages, information or content ("Postings") posted on the Site by users and assumes no responsibility or liability relating to any such Postings. Notwithstanding the above, WRS may from time to time monitor the Postings on the Site and may decline to accept and/or remove any Postings. You understand and agree not to use any functionality provided by the Site to post content or initiate communications that contain: (i) Any unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, profane, hateful, racially, ethnically or otherwise objectionable material of any kind, including, but not limited to, any material which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national or international law; (ii) Advertisements or solicitations of any kind; (iii) Impersonate others or provide any kind of false information; (iv) Personal information such as messages which state phone numbers, account numbers, addresses, or employer references.; (v) Messages by non-spokesperson employees of WRS purporting to speak on behalf of WRS or containing confidential information or expressing opinions concerning Jetsetter; (vi) Messages that offer unauthorized downloads of any copyrighted or private information; (vii) Multiple messages placed within individual folders by the same user restating the same point; (viii) Chain letters of any kind; or (ix) Identical (or substantially similar) messages to multiple recipients advertising any product or service, expressing a political or other similar message, or any other type of unsolicited commercial message. This prohibition includes but is not limited to a) Using WRS to send messages to people who don't know you or who are unlikely to recognize you as a known contact; b) Using WRS to connect to people who don't know you and then sending unsolicited promotional messages to those direct connections without their permission; and c) Sending messages to distribution lists, newsgroup aliases, or group aliases.<br />
        <br />
        <b>13. Links</b><br />
        The Site or third parties may provide links to other World Wide Web sites or resources. Because WRS has no control over such sites and resources, you acknowledge and agree that WRS is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that WRS shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.<br />
        <br />
        <b>14. Access To Password Protected/Secure Areas</b><br />
        Access to and use of password protected and/or secure areas of the Site is restricted to authorized users only. Unauthorized individuals attempting to access these areas of the Site may be subject to prosecution.<br />
        <br />
        <b>15. Modification and Notification of Changes</b><br />
        WRS reserves the right to make changes to the Site, related policies and agreements, this ToU and the Privacy Policy at any time. If WRS makes a material modification to this ToU, it may notify you by: (i) displaying a prominent announcement above the text of this ToU or the Privacy Policy, as appropriate, for thirty (30) days, being deemed sufficient notification, of such changes. After notice of a modification to the ToU or the Privacy Policy has been posted for 30 days, the notice will be removed. If you have not used the Site for more than 30 days, you should check the ToU and/or Privacy Policy prior to any further use of the Site. If you choose to continue using the Site, you agree that by doing so you will be deemed to accept the new ToU or Privacy Policy, as relevant.<br />
        <br />
        <b>16. Trademarks</b><br />
        The trademarks, logos and service marks ("Marks") displayed on the Site are the property of WRS and other parties. Users are prohibited from using any Marks for any purpose including, but not limited to use as metatags on other pages or sites on the World Wide Web without the written permission of Jetsetter or such third party which may own the Marks. All information and content including any software programs available on or through the Site ("Content") is protected by copyright. Users are prohibited from modifying, copying, distributing, transmitting, displaying, publishing, selling, licensing, creating derivative works or using any Content available on or through the Site for commercial or public purposes.<br />
        <br />
        <b>17. Survival of Terms After Agreement Ends</b><br />
        Notwithstanding any other provisions of this ToU, or any general legal principles to the contrary, any provision of this ToU that imposes or contemplates continuing obligations on a party will survive the expiration or termination of this ToU.<br />
        <br />
        <b>18. General</b><br />
        If any of these conditions are deemed invalid, void, or for any reason unenforceable, the parties agree that the court should endeavor to give effect to the partie's intentions as reflected in the provision, and the unenforceable condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition. Headings are for reference purposes only and do not limit the scope or extent of such section. This ToU and the relationship between you and WRS will be governed by the laws of the India without regard to its conflict of law provisions. You and WRS agree to submit to the personal jurisdiction of the courts located in Gurgaon jurisdiction with respect to any legal proceedings that may arise in connection with this ToU. The failure of WRS to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. WRS does not guarantee it will take action against all breaches of this ToU. Except as otherwise expressly provided in this ToU, there shall be no third-party beneficiaries to this ToU. This ToU constitutes the entire agreement between you and WRS and governs your use of the Site, superseding any prior agreements between you and WRS with respect to the Site. </p>
    </div>
  </div>
</div>
<?php include("footer_sub_menu.php"); ?>
</body>
</html>